### ISSUE TITLE
Unable to use in two simultaneous instances

### ISSUE THREAD

**Issue by backspace** [f34nk/modest_ex#17]
Hey, thanks for this library, I chose to start a new application in Elixir without ensuring something like this existed, so I’m glad it does!

I feel like a comparative neophyte when it comes to Elixir/Erlang and Phoenix so it may be that I’m missing something obvious, but I’ve found that I can’t use `modest_ex` when it’s already running in another process. For instance, if I’m running `mix phx.server` so I can interact with the live application, when I run `mix test` to execute the tests, I get this error:

```
** (Mix) Could not start application modest_ex: exited in: ModestEx.Safe.start(:normal, [])
    ** (EXIT) exited in: :gen_server.call(:boot_server, {:add, {{255, 255, 255, 255}, {127, 0, 0, 1}}})
        ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
```

If I kill the server process and run `mix test`, then the tests pass with no problem.

I’ve tried a few things:
* `runtime: false` in `mix.exs#deps`
* `:modest_ex` in `mix.exs#application extra_applications`
* `Application.ensure_all_started(:modest_ex)` in `test_helper.exs`

I’m running this with Elixir 1.9.0 and Phoenix 1.4.7.

**Comment by backspace** [comment]
hmm I’m even finding now that I can’t have more than one test that exercises `ModestEx`, as I get messages like this error:

```
21:49:11.600 [error] GenServer ModestEx.Safe.Cnode terminating
** (ArgumentError) all arguments for System.cmd/3 must be binaries
    (elixir) lib/system.ex:782: System.cmd/3
    (nodex) lib/nodex/cnode.ex:132: Nodex.Cnode.terminate/2
    (stdlib) gen_server.erl:673: :gen_server.try_terminate/3
    (stdlib) gen_server.erl:858: :gen_server.terminate/10
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:nodedown, :"e5a463a0@127.0.0.1"}
```

ETA actually, I was incorrect, the second test was just producing a `ModestEx` error 😬

**Comment by f34nk** [comment]
Hey Buck, looking at the error message this is a `nodex` issue. Are you able to provide an example to demonstrate this? I would need some time to look at this. Maybe also ask this in the [forum](https://elixirforum.com/t/modestex-pipeable-transformations-on-html-strings-with-css-selectors/12793). I remember there is a `nodex` thread [here](https://elixirforum.com/t/nodex-helper-modules-around-distributed-elixir-and-c-nodes/9350).
Frank

**Comment by backspace** [comment]
Thanks for the response!

I made [this repository](https://github.com/backspace/modest_ex_concurrency) to reproduce the problem. In [e326b53](https://github.com/backspace/modest_ex_concurrency/commit/e326b53bbe5ff679fa945a7d689cc6ed7f0c95fc), I added the `modest_ex` dependency and a simple test to exercise it, and [the tests passed](https://travis-ci.com/backspace/modest_ex_concurrency/builds/117578218#L6799).

Then in [418d51c](https://github.com/backspace/modest_ex_concurrency/commit/418d51c0520abd1fc7b4579bf7c594dc45e64021) I added a `before_script` on Travis CI to start the Phoenix server with `mix phx.server &`, so it’s running in the background. Then [the tests don’t run](https://travis-ci.com/backspace/modest_ex_concurrency/builds/117578600#L685-L693).

However, the error is different than the one I see locally and there are some CMake errors earlier in the log, so it may be that this isn’t a true reproduction. But when I have `mix phx.server` running locally and run `mix test` in another terminal, I do get a similar error:

```
** (Mix) Could not start application modest_ex: exited in: ModestEx.Safe.start(:normal, [])
    ** (EXIT) exited in: :gen_server.call(:boot_server, {:add, {{255, 255, 255, 255}, {127, 0, 0, 1}}})
        ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
```

I’m experiencing this on macOS 10.14.4. It’s not a disaster as I’ve just been killing the server when I want to run the tests.
